### ISSUE TITLE
Repo Structure

### ISSUE THREAD

**Issue by gjurgiel** [rambunction4330/CppResources#3]
I'm thinking of deleting all the links out of the "resources" section of the email, and removing all the paragraphs out of the repo. That way l'll just have the email link them to here, and we can update this a needed.

**Comment by theVerySharpFlat** [comment]
Wait. Why are we deleting the links? Isn't that the point of the repo?

**Comment by gjurgiel** [comment]
No, I just mean that since this was originally just going to be an email we should separate the two. Leave the repo with the links and I'll just send the paragraphs at the beginning and end. That way I only have to like to the repo in the email, and the repo can be left as just a list of links we can expand upon (with a bit of explanation).

**Comment by theVerySharpFlat** [comment]
Yeah! That makes sense!

**Comment by gjurgiel** [comment]
If it's ok with you, I might rename the repo to a more general `Resources` to give the option of adding sections for more general frc stuff. and not just C++.

**Comment by theVerySharpFlat** [comment]
> If it's ok with you, I might rename the repo to a more general `Resources` to give the option of adding sections for more general frc stuff. and not just C++.

sounds good

**Comment by theVerySharpFlat** [comment]
Yeah that makes sense
