### ISSUE TITLE
Add Images

### ISSUE THREAD

**Issue by theVerySharpFlat** [rambunction4330/CppResources#4]
Maybe it would be inspiring to add some inspiring images to this repo.

Something like this maybe?

![IMG_7200](https://user-images.githubusercontent.com/74067227/170883064-822870a9-0b3f-4069-9db4-056e7a4f9157.jpg)

The row of computers and the junk piled up will make them in awe of our technological capability and vast superiority to all other departments.

**Comment by gjurgiel** [comment]
Definelty! I also suggest this one.
![IMG_4793-1](https://user-images.githubusercontent.com/59634069/171077568-52b979e4-686c-4c88-bd6a-9ece768233d9.jpg)
e
